services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: myapp
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuser123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
    networks:
      - databases_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appuser123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/logs:/var/log/postgresql
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    networks:
      - databases_network
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d myapp"]
      interval: 30s
      timeout: 10s
      retries: 3

  # CloudBeaver (Web-based DBeaver) for database management
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    environment:
      CB_ADMIN_NAME: admin
      CB_ADMIN_PASSWORD: admin123
      CB_SERVER_NAME: CloudBeaver Database Manager
      CB_LOCAL_HOST_ADDR: 0.0.0.0
    ports:
      - "8081:8978"
    volumes:
      - ./cloudbeaver/workspace:/opt/cloudbeaver/workspace
      - ./cloudbeaver/logs:/opt/cloudbeaver/logs
    networks:
      - databases_network
    depends_on:
      - mysql
      - postgres

networks:
  databases_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  postgres_data:
    driver: local
  cloudbeaver_data:
    driver: local
